url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Aymeric AKA" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: a.bourguilleau@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Add description here
# author:
google_analytics: UA-111111111-1
# twitter:
  # username: 
  # card: summary #keep this to generate a twitter share card
# more on https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

sass:

  sass_dir: assets/css
  style: compressed
    # load_paths:
        # - _sass
        # - /Users/kallyannybun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootstrap-4.3.1/assets/stylesheets